### ISSUE TITLE
HELP NEEDED

### ISSUE THREAD

**Issue by satyam-mahajan** [Vaishnvee-Shinde/BanckingSystem#1]
when i run your code transfer.php is not working .please help me

**Comment by Vaishnvee-Shinde** [comment]
Hey Please check your Database name , password  and other required files. *check file name and file name entered in code.. I think  this will solve your issue.. Still I have  updated the code.

**Comment by satyam-mahajan** [comment]
If problem is not fixed by me.then you can help me to resolve it?
Thanking you...!!!

**Comment by Vaishnvee-Shinde** [comment]
Yes Sure !!
